package com.terraforged.mod.worldgen.biome.rules;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** One biomes's terrain / subterrain / zone placement rule (JSON body after ASM header). */
public final class BiomeRule {
    public static final String ZONE_NEAR_ACTIVE_VOLCANO = "near_active_volcano";
    /** Optional: biome may spawn near a dormant volcano. Unflagged biomes may still spawn near dormant. */
    public static final String ZONE_NEAR_DORMANT_VOLCANO = "near_dormant_volcano";

    public final String biome;
    public final boolean canBeOnSlope;
    public final List<String> climateTags;
    public final Map<String, Float> terrains;
    public final Map<String, Float> subterrains;
    /**
     * Zone-scoped flags — constrain to a local area, not whole terrain.
     * {@link #ZONE_NEAR_ACTIVE_VOLCANO}: only near a volcano (active or dormant), nowhere else.
     * {@link #ZONE_NEAR_DORMANT_VOLCANO}: optional; only near dormant.
     */
    public final Map<String, ZoneFlag> zoneFlags;
    public final boolean autoGenerated;

    public BiomeRule(
            String biome,
            boolean canBeOnSlope,
            List<String> climateTags,
            Map<String, Float> terrains,
            Map<String, Float> subterrains,
            Map<String, ZoneFlag> zoneFlags,
            boolean autoGenerated) {
        this.biome = biome == null ? "" : biome.trim().toLowerCase(Locale.ROOT);
        this.canBeOnSlope = canBeOnSlope;
        this.climateTags = climateTags == null || climateTags.isEmpty()
                ? List.of()
                : List.copyOf(climateTags);
        this.terrains = terrains == null || terrains.isEmpty()
                ? Map.of()
                : Collections.unmodifiableMap(new LinkedHashMap<>(terrains));
        this.subterrains = subterrains == null || subterrains.isEmpty()
                ? Map.of()
                : Collections.unmodifiableMap(new LinkedHashMap<>(subterrains));
        this.zoneFlags = zoneFlags == null || zoneFlags.isEmpty()
                ? Map.of()
                : Collections.unmodifiableMap(new LinkedHashMap<>(zoneFlags));
        this.autoGenerated = autoGenerated;
    }

    public boolean hasTerrains() {
        return !this.terrains.isEmpty();
    }

    public boolean requiresZone(String flagId) {
        ZoneFlag z = this.zoneFlags.get(flagId);
        return z != null && z.enabled();
    }

    public ZoneFlag zone(String flagId) {
        return this.zoneFlags.get(flagId);
    }

    public float terrainChance(String concreteTerrain) {
        if (concreteTerrain == null || concreteTerrain.isBlank()) {
            return 0.0F;
        }
        Float direct = this.terrains.get(concreteTerrain.toLowerCase(Locale.ROOT));
        return direct == null ? 0.0F : Math.max(0.0F, direct);
    }

    public float subterrainChance(String subterrain) {
        if (subterrain == null || subterrain.isBlank() || this.subterrains.isEmpty()) {
            return this.subterrains.isEmpty() ? 1.0F : 0.0F;
        }
        Float c = this.subterrains.get(subterrain.toLowerCase(Locale.ROOT));
        return c == null ? 0.0F : Math.max(0.0F, c);
    }

    /**
     * Zone flag: applies to a local footprint (radius), not an entire terrain type.
     * Example: volcanic plains only in the ring around an active / dormant volcano.
     */
    public record ZoneFlag(boolean enabled, float radiusBlocks, float chance) {
        public static ZoneFlag enabled(float radiusBlocks, float chance) {
            return new ZoneFlag(true, Math.max(8.0F, radiusBlocks), Math.max(0.0F, chance));
        }

        public static ZoneFlag disabled() {
            return new ZoneFlag(false, 0.0F, 0.0F);
        }
    }
}
