package com.terraforged.mod.worldgen.biome.rules;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonSyntaxException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Load / save biome rule files with ASM header + .broken quarantine. */
public final class BiomeRuleIO {
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();

    private BiomeRuleIO() {
    }

    public record LoadResult(BiomeRule rule, String error) {
        public boolean ok() {
            return this.rule != null && this.error == null;
        }
    }

    public static LoadResult load(Path file) {
        try {
            String raw = Files.readString(file, StandardCharsets.UTF_8);
            if (!raw.isEmpty() && raw.charAt(0) == '\uFEFF') {
                raw = raw.substring(1);
            }
            String[] lines = raw.split("\\R", 2);
            if (lines.length < 2) {
                return new LoadResult(null, "file too short: need ASM header line + JSON body");
            }
            try {
                BiomeRuleHeader.parseOrThrow(lines[0]);
            } catch (IllegalArgumentException e) {
                return new LoadResult(null, e.getMessage());
            }
            String body = lines[1].trim();
            if (body.isEmpty()) {
                return new LoadResult(null, "empty JSON body after header");
            }
            try {
                JsonObject obj = JsonParser.parseString(body).getAsJsonObject();
                return parseBody(obj);
            } catch (JsonSyntaxException | IllegalStateException e) {
                return new LoadResult(null, "invalid JSON: " + e.getMessage());
            }
        } catch (IOException e) {
            return new LoadResult(null, "io error: " + e.getMessage());
        }
    }

    public static LoadResult parseBody(JsonObject obj) {
        List<String> missing = new ArrayList<>();
        if (!obj.has("biome") || !obj.get("biome").isJsonPrimitive()) {
            missing.add("biome");
        }
        if (!obj.has("terrains") || !obj.get("terrains").isJsonObject() || obj.getAsJsonObject("terrains").entrySet().isEmpty()) {
            missing.add("terrains (non-empty object)");
        }
        if (!missing.isEmpty()) {
            return new LoadResult(null, "missing required fields: " + String.join(", ", missing));
        }
        String biome = obj.get("biome").getAsString();
        // Legacy field kept for file compat; ignored at runtime.
        boolean slope = !obj.has("can_be_on_slope") || obj.get("can_be_on_slope").getAsBoolean();
        List<String> tags = readStringList(obj, "climate_tags");
        Map<String, Float> terrains = readChanceMap(obj.getAsJsonObject("terrains"));
        Map<String, Float> subterrains = obj.has("subterrains") && obj.get("subterrains").isJsonObject()
                ? readChanceMap(obj.getAsJsonObject("subterrains"))
                : Map.of();
        Map<String, BiomeRule.ZoneFlag> zones = obj.has("zone_flags") && obj.get("zone_flags").isJsonObject()
                ? readZoneFlags(obj.getAsJsonObject("zone_flags"))
                : Map.of();
        boolean auto = obj.has("auto_generated") && obj.get("auto_generated").getAsBoolean();
        BiomeRule rule = new BiomeRule(biome, slope, tags, terrains, subterrains, zones, auto);
        if (!rule.hasTerrains()) {
            return new LoadResult(null, "terrains resolved empty");
        }
        return new LoadResult(rule, null);
    }

    public static void write(Path file, BiomeRule rule) throws IOException {
        Files.createDirectories(file.getParent());
        JsonObject obj = new JsonObject();
        obj.addProperty("biome", rule.biome);
        obj.addProperty("can_be_on_slope", rule.canBeOnSlope);
        JsonArray tags = new JsonArray();
        for (String t : rule.climateTags) {
            tags.add(t);
        }
        obj.add("climate_tags", tags);
        obj.add("terrains", toChanceObject(rule.terrains));
        obj.add("subterrains", toChanceObject(rule.subterrains));
        obj.add("zone_flags", toZoneObject(rule.zoneFlags));
        obj.addProperty("auto_generated", rule.autoGenerated);
        String json = GSON.toJson(obj);
        String out = BiomeRuleHeader.buildLine(BiomeRuleHeader.generateToken()) + "\n" + json + "\n";
        Files.writeString(file, out, StandardCharsets.UTF_8);
    }

    /**
     * Quarantine broken file as {@code name.json.broken} with error comment prepended, then delete original path
     * so a fresh rule can be written.
     */
    public static void quarantineBroken(Path file, String reason) throws IOException {
        if (!Files.exists(file)) {
            return;
        }
        Path broken = Path.of(file.toString() + ".broken");
        String old = Files.readString(file, StandardCharsets.UTF_8);
        if (!old.isEmpty() && old.charAt(0) == '\uFEFF') {
            old = old.substring(1);
        }
        String comment = "# BROKEN: " + (reason == null ? "unknown" : reason.replace('\n', ' ')) + "\n";
        Files.writeString(broken, comment + old, StandardCharsets.UTF_8);
        Files.deleteIfExists(file);
    }

    private static List<String> readStringList(JsonObject obj, String key) {
        if (!obj.has(key) || !obj.get(key).isJsonArray()) {
            return List.of();
        }
        List<String> out = new ArrayList<>();
        for (JsonElement el : obj.getAsJsonArray(key)) {
            if (el.isJsonPrimitive()) {
                out.add(el.getAsString().toLowerCase(Locale.ROOT));
            }
        }
        return out;
    }

    private static Map<String, Float> readChanceMap(JsonObject obj) {
        LinkedHashMap<String, Float> out = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> e : obj.entrySet()) {
            String key = e.getKey().toLowerCase(Locale.ROOT);
            JsonElement v = e.getValue();
            float chance = 1.0F;
            if (v.isJsonObject() && v.getAsJsonObject().has("chance")) {
                chance = v.getAsJsonObject().get("chance").getAsFloat();
            } else if (v.isJsonPrimitive() && v.getAsJsonPrimitive().isNumber()) {
                chance = v.getAsFloat();
            }
            if (chance > 0.0F) {
                out.put(key, chance);
            }
        }
        return out;
    }

    private static JsonObject toChanceObject(Map<String, Float> map) {
        JsonObject obj = new JsonObject();
        for (Map.Entry<String, Float> e : map.entrySet()) {
            JsonObject entry = new JsonObject();
            entry.addProperty("chance", e.getValue());
            obj.add(e.getKey(), entry);
        }
        return obj;
    }

    private static Map<String, BiomeRule.ZoneFlag> readZoneFlags(JsonObject obj) {
        LinkedHashMap<String, BiomeRule.ZoneFlag> out = new LinkedHashMap<>();
        for (Map.Entry<String, JsonElement> e : obj.entrySet()) {
            String key = e.getKey().toLowerCase(Locale.ROOT);
            JsonElement v = e.getValue();
            if (v.isJsonPrimitive() && v.getAsJsonPrimitive().isBoolean()) {
                if (v.getAsBoolean()) {
                    out.put(key, BiomeRule.ZoneFlag.enabled(640.0F, 1.0F));
                }
                continue;
            }
            if (!v.isJsonObject()) {
                continue;
            }
            JsonObject z = v.getAsJsonObject();
            boolean enabled = !z.has("enabled") || z.get("enabled").getAsBoolean();
            if (!enabled) {
                continue;
            }
            float radius = z.has("radius_blocks") ? z.get("radius_blocks").getAsFloat() : 640.0F;
            float chance = z.has("chance") ? z.get("chance").getAsFloat() : 1.0F;
            out.put(key, BiomeRule.ZoneFlag.enabled(radius, chance));
        }
        return out;
    }

    private static JsonObject toZoneObject(Map<String, BiomeRule.ZoneFlag> map) {
        JsonObject obj = new JsonObject();
        for (Map.Entry<String, BiomeRule.ZoneFlag> e : map.entrySet()) {
            BiomeRule.ZoneFlag z = e.getValue();
            JsonObject entry = new JsonObject();
            entry.addProperty("enabled", z.enabled());
            entry.addProperty("radius_blocks", z.radiusBlocks());
            entry.addProperty("chance", z.chance());
            obj.add(e.getKey(), entry);
        }
        return obj;
    }
}
