package com.terraforged.mod.worldgen.biome.rules;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** One biomes's terrain / subterrain placement rule (JSON body after ASM header). */
public final class BiomeRule {
    public final String biome;
    public final boolean canBeOnSlope;
    public final List<String> climateTags;
    public final Map<String, Float> terrains;
    public final Map<String, Float> subterrains;
    public final boolean autoGenerated;

    public BiomeRule(
            String biome,
            boolean canBeOnSlope,
            List<String> climateTags,
            Map<String, Float> terrains,
            Map<String, Float> subterrains,
            boolean autoGenerated) {
        this.biome = biome == null ? "" : biome.trim().toLowerCase(Locale.ROOT);
        this.canBeOnSlope = canBeOnSlope;
        this.climateTags = climateTags == null || climateTags.isEmpty()
                ? List.of()
                : List.copyOf(climateTags);
        this.terrains = terrains == null || terrains.isEmpty()
                ? Map.of()
                : Collections.unmodifiableMap(new LinkedHashMap<>(terrains));
        this.subterrains = subterrains == null || subterrains.isEmpty()
                ? Map.of()
                : Collections.unmodifiableMap(new LinkedHashMap<>(subterrains));
        this.autoGenerated = autoGenerated;
    }

    public boolean hasTerrains() {
        return !this.terrains.isEmpty();
    }

    public float terrainChance(String concreteTerrain) {
        if (concreteTerrain == null || concreteTerrain.isBlank()) {
            return 0.0F;
        }
        Float direct = this.terrains.get(concreteTerrain.toLowerCase(Locale.ROOT));
        return direct == null ? 0.0F : Math.max(0.0F, direct);
    }

    public float subterrainChance(String subterrain) {
        if (subterrain == null || subterrain.isBlank() || this.subterrains.isEmpty()) {
            return this.subterrains.isEmpty() ? 1.0F : 0.0F;
        }
        Float c = this.subterrains.get(subterrain.toLowerCase(Locale.ROOT));
        return c == null ? 0.0F : Math.max(0.0F, c);
    }
}
