# Applies biome-terrain review heuristics into biome-terrain-integration.toml
# using TerrainGroup sections (group.*) so the runtime expander stays the source of truth.
#
# Loop:
#   1. generate-biome-terrain-review.ps1  -> docs/biome-terrain-review.md
#   2. (optional human edits to review / this script's rule sets)
#   3. apply-biome-terrain-review.ps1     -> Terrain/biome-terrain-integration.toml
#   4. generate again to verify gaps closed
#
# Usage:
#   powershell -File scripts/apply-biome-terrain-review.ps1
#   powershell -File scripts/apply-biome-terrain-review.ps1 -WhatIf

[CmdletBinding(SupportsShouldProcess = $true)]
param()

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$outPath = Join-Path $root 'Forge\main\resources\defaultconfigs\NewTerraForged\Terrain\biome-terrain-integration.toml'

# Mesa / terracotta family — badlands whitelist only
$mesa = @(
    'minecraft:badlands', 'minecraft:wooded_badlands', 'minecraft:eroded_badlands',
    'terralith:savanna_badlands', 'terralith:snowy_badlands', 'terralith:warped_mesa', 'terralith:white_mesa',
    'terralith:bryce_canyon', 'terralith:sandstone_valley', 'terralith:ancient_sands', 'terralith:gravel_desert',
    'terralith:red_oasis', 'terralith:desert_canyon', 'terralith:painted_mountains',
    'byg:sierra_badlands', 'byg:atacama_outback',
    'regions_unexplored:outback', 'regions_unexplored:arid_mountains', 'regions_unexplored:wooded_arid_mountains',
    'regions_unexplored:barley_fields',
    'biomesoplenty:lush_desert', 'biomesoplenty:dryland', 'biomesoplenty:volcanic_plains'
)

$beach = @('minecraft:beach', 'minecraft:stony_shore', 'minecraft:snowy_beach')

$swamp = @(
    'minecraft:swamp', 'minecraft:mangrove_swamp',
    'biomesoplenty:bayou', 'biomesoplenty:marsh', 'biomesoplenty:wetland', 'biomesoplenty:bog',
    'byg:bayou', 'byg:cypress_swamplands', 'byg:white_mangrove_marshes', 'byg:embur_bog',
    'regions_unexplored:bayou', 'regions_unexplored:giant_bayou', 'regions_unexplored:fen', 'regions_unexplored:fungal_fen',
    'terralith:orchid_swamp', 'terralith:ice_marsh'
)

$jungle = @(
    'minecraft:jungle', 'minecraft:sparse_jungle', 'minecraft:bamboo_jungle',
    'biomesoplenty:bamboo_grove', 'biomesoplenty:fungal_jungle', 'biomesoplenty:rainforest',
    'biomesoplenty:rocky_rainforest', 'biomesoplenty:tropics',
    'byg:tropical_rainforest', 'byg:temperate_rainforest',
    'regions_unexplored:bamboo_forest', 'regions_unexplored:old_growth_rainforest',
    'regions_unexplored:rainforest', 'regions_unexplored:tropics',
    'terralith:amethyst_rainforest', 'terralith:jungle_mountains', 'terralith:rocky_jungle', 'terralith:tropical_jungle'
)

$alpineExtra = @('terralith:frozen_tundra')

$volcanoWl = @(
    'biomesoplenty:volcano', 'biomesoplenty:volcanic_plains',
    'terralith:volcanic_crater', 'terralith:volcanic_peaks', 'terralith:ashen_savanna',
    'byg:basalt_barrera', 'byg:magma_wastes', 'minecraft:basalt_deltas'
)

function Format-TomlList([string[]]$ids) {
    $lines = @('[' )
    foreach ($id in $ids) {
        $lines += "  `"$id`","
    }
    if ($ids.Count -gt 0) {
        $lines[-1] = $lines[-1].TrimEnd(',')
    }
    $lines += ']'
    return ($lines -join "`n")
}

function Write-Section([System.Collections.Generic.List[string]]$buf, [string]$name, [string]$mode, [string[]]$ids) {
    $buf.Add('')
    $buf.Add("[$name]")
    $buf.Add("$mode = $(Format-TomlList $ids)")
}

$buf = [System.Collections.Generic.List[string]]::new()
$buf.Add('# NewTerraForged — biome ↔ terrain integration')
$buf.Add('# Autogenerated by scripts/apply-biome-terrain-review.ps1 — edit rule sets there, then re-apply.')
$buf.Add('# Groups expand via TerrainGroup at load (nested TOML [group.plains] is supported).')
$buf.Add('#')
$buf.Add('# whitelist — if non-empty, ONLY these biomes may appear on this terrain.')
$buf.Add('# blacklist — these biomes never appear on this terrain.')
$buf.Add('# Mesa family: badlands whitelist only. Jungle/swamp: plains/dales/steppe OK; blocked on hills+.')

# Lowland: mesa + beach ban; swamp/jungle allowed
$lowlandBl = @($mesa + $beach)
Write-Section $buf 'group.plains' 'blacklist' $lowlandBl
Write-Section $buf 'group.dales' 'blacklist' $lowlandBl

# Upland: also ban swamp + jungle
$uplandBl = @($swamp + $mesa + $beach + $jungle)
Write-Section $buf 'group.hills' 'blacklist' $uplandBl
Write-Section $buf 'group.plateau' 'blacklist' $uplandBl

$alpineBl = @($swamp + $alpineExtra + $mesa + $beach + $jungle)
Write-Section $buf 'group.torridonian' 'blacklist' $alpineBl
Write-Section $buf 'group.dolomites' 'blacklist' $alpineBl
Write-Section $buf 'group.mountains' 'blacklist' $alpineBl
Write-Section $buf 'group.mountains_ridge' 'blacklist' $alpineBl

Write-Section $buf 'group.badlands' 'whitelist' $mesa

# Islands: mesa ban on all; swamp/jungle OK on flats/hills; block on mountains/plateau
Write-Section $buf 'group.island' 'blacklist' $mesa
Write-Section $buf 'island_mountains' 'blacklist' @($swamp + $mesa + $beach)
Write-Section $buf 'island_plateau' 'blacklist' @($swamp + $mesa + $beach)
Write-Section $buf 'island_volcano' 'whitelist' $volcanoWl
Write-Section $buf 'laguna' 'blacklist' @(
    'minecraft:badlands', 'minecraft:wooded_badlands', 'minecraft:eroded_badlands',
    'terralith:savanna_badlands', 'terralith:snowy_badlands', 'terralith:warped_mesa', 'terralith:white_mesa'
)

$text = ($buf -join "`n") + "`n"
if ($PSCmdlet.ShouldProcess($outPath, 'Write biome-terrain-integration.toml')) {
    Set-Content -Path $outPath -Value $text -Encoding UTF8
    Write-Output "Wrote $outPath"
} else {
    Write-Output "WhatIf: would write $($buf.Count) lines to $outPath"
}
