#!/usr/bin/env python3
"""
Hand-curated NewTerraForged biome terrain + cave Cond defaults writer (1.18.2).

Every biome below is an explicit catalog entry — this script WRITES JSON files from
that catalog. It does NOT invent terrains from fuzzy path-token loops at runtime.

Usage:
  python tools/generate_curated_defaults.py
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SURFACE_ROOT = ROOT / (
    "Forge/main/resources/defaultconfigs/NewTerraForged/"
    "Terrain/Terrain_rules/Defaults"
)
SURFACE_BY_ID = SURFACE_ROOT / "by_id"
CAVE_ROOT = ROOT / (
    "Forge/main/resources/defaultconfigs/NewTerraForged/Cave_configs/Biomes"
)

NEAR_ACTIVE_VOLCANO = {
    "near_active_volcano": {
        "enabled": True,
        "radius_blocks": 640,
        "chance": 1.0,
    }
}

# ---------------------------------------------------------------------------
# Surface helpers — builders only; each biome still lists explicit terrains.
# ---------------------------------------------------------------------------

def S(
    biome: str,
    note: str,
    climates: list[str],
    terrains: dict[str, float],
    *,
    slope: bool = True,
    subterrains: dict[str, float] | None = None,
    zones: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """One explicit surface BiomeRule body (+ comment note for maintainers)."""
    return {
        "_note": note,
        "biome": biome,
        "can_be_on_slope": slope,
        "climate_tags": list(climates),
        "terrains": dict(terrains),
        "subterrains": dict(subterrains or {}),
        "zone_flags": dict(zones or {}),
        "auto_generated": False,
    }


def hills_plateau(w_h1=1.0, w_h2=0.9, w_p=0.85, w_ih=0.5, w_ip=0.45) -> dict[str, float]:
    return {
        "hills_1": w_h1,
        "hills_2": w_h2,
        "plateau": w_p,
        "island_hills": w_ih,
        "island_plateau": w_ip,
    }


def mountains_full() -> dict[str, float]:
    return {
        "mountains_1": 1.0,
        "mountains_2": 1.0,
        "mountains_3": 1.0,
        "mountains_ridge_1": 0.8,
        "mountains_ridge_2": 0.8,
        "dolomites": 0.6,
        "torridonian": 0.5,
        "island_mountains": 0.6,
    }


def mountain_subs() -> dict[str, float]:
    return {
        "mountain_body": 0.6,
        "mountain_foothill": 0.5,
        "bare_mountain": 0.4,
    }


def peak_subs() -> dict[str, float]:
    return {
        "mountain_peak": 0.7,
        "bare_mountain_peak": 0.5,
        "mountain_body": 0.5,
        "mountain_foothill": 0.4,
    }


def plains_dales(w_p=1.0, w_d=0.6, w_if=0.5, w_s=0.0) -> dict[str, float]:
    out = {"plains": w_p, "dales": w_d, "island_flats": w_if}
    if w_s > 0:
        out["steppe"] = w_s
    return out


def jungle_low() -> dict[str, float]:
    return {"plains": 1.0, "dales": 0.85, "hills_1": 0.55, "island_flats": 0.45}


def desert_flat() -> dict[str, float]:
    return {"steppe": 1.0, "plains": 0.7, "island_flats": 0.4}


def badlands_terr() -> dict[str, float]:
    return {"badlands": 1.0}


def badlands_subs() -> dict[str, float]:
    return {"canyon": 0.6, "desert_canyon": 0.4}


def cliff_mount() -> dict[str, float]:
    return {
        "mountains_1": 1.0,
        "mountains_2": 0.85,
        "mountains_ridge_1": 0.7,
        "torridonian": 0.55,
        "island_mountains": 0.5,
    }


def island_float() -> dict[str, float]:
    return {
        "island_flats": 1.0,
        "island_hills": 0.85,
        "island_plateau": 0.7,
        "plains": 0.4,
        "hills_1": 0.35,
    }


# ===========================================================================
# A) SURFACE CATALOG — every entry is explicit (Terralith wiki + vanilla).
# Climate reasoning uses wiki temp/downfall where available.
# ===========================================================================

SURFACE: list[dict[str, Any]] = [
    # --- Terralith ---
    S(
        "terralith:alpha_islands",
        "Classic alpha grass islands (T0.7/D0.8) — floating island kit, temperate/wet.",
        ["temperate", "wet"],
        island_float(),
        slope=True,
    ),
    S(
        "terralith:alpha_islands_winter",
        "Winter alpha islands (T0/D0.75) — same island kit, snowy/cold.",
        ["snowy", "cold"],
        island_float(),
        slope=True,
    ),
    S(
        "terralith:alpine_grove",
        "Snowy alpine grove (T-0.2/D0.8) — grove hills, never full mountains.",
        ["cold", "snowy", "alpine"],
        {"hills_1": 1.0, "hills_2": 0.8, "dales": 0.5, "island_hills": 0.5},
        slope=True,
    ),
    S(
        "terralith:alpine_highlands",
        "Bushy highlands (T0.45/D0.1) — hills+plateau ONLY, NEVER mountains.",
        ["cold", "temperate", "alpine"],
        hills_plateau(),
        slope=True,
    ),
    S(
        "terralith:amethyst_canyon",
        "Hot wet amethyst canyon (T0.95/D0.9) — canyon badlands + jungle climate.",
        ["hot", "jungle", "wet"],
        badlands_terr(),
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "terralith:amethyst_rainforest",
        "Amethyst rainforest (T0.95/D0.9) — jungle lowlands + light hills.",
        ["hot", "jungle", "wet"],
        jungle_low(),
        slope=True,
    ),
    S(
        "terralith:ancient_sands",
        "Ancient desert sands (T2/D0) — desert flats/steppe.",
        ["hot", "desert"],
        desert_flat(),
        slope=False,
    ),
    S(
        "terralith:arid_highlands",
        "Arid highlands (T1.6/D0.1) — dry hills/plateau, hot.",
        ["hot", "desert"],
        hills_plateau(1.0, 0.85, 0.9, 0.45, 0.5),
        slope=True,
    ),
    S(
        "terralith:ashen_savanna",
        "Ash plains near volcanoes (T1/D0) — steppe/plains + near_active_volcano, NOT the cone.",
        ["hot", "volcanic"],
        {"steppe": 1.0, "plains": 0.85, "island_flats": 0.4},
        slope=False,
        zones=NEAR_ACTIVE_VOLCANO,
    ),
    S(
        "terralith:basalt_cliffs",
        "Basalt coastal cliffs (T0.5/D0.3) — ridge/cliff mountains + beach fringe.",
        ["temperate", "volcanic"],
        {**cliff_mount(), "beach": 0.35},
        slope=True,
        subterrains={"bare_mountain": 0.55, "mountain_body": 0.4, "ocean_beach": 0.3},
    ),
    S(
        "terralith:birch_taiga",
        "Birch taiga (T0.22/D0.2) — cold taiga hills/dales.",
        ["cold", "temperate"],
        {"dales": 1.0, "hills_1": 0.75, "plains": 0.45, "island_hills": 0.4},
        slope=True,
    ),
    S(
        "terralith:blooming_plateau",
        "Flower plateau (T0.5/D0.8) — plateau primary, wet temperate.",
        ["temperate", "wet"],
        {"plateau": 1.0, "hills_1": 0.55, "island_plateau": 0.6, "plains": 0.35},
        slope=True,
    ),
    S(
        "terralith:blooming_valley",
        "Flower valley (T0.7/D0.8) — plains/dales valley floor.",
        ["temperate", "wet"],
        plains_dales(1.0, 0.9, 0.45),
        slope=False,
    ),
    S(
        "terralith:brushland",
        "Hot brushland (T1.2/D0.2) — steppe/plains scrub.",
        ["hot"],
        {"steppe": 1.0, "plains": 0.7, "hills_1": 0.35, "island_flats": 0.4},
        slope=False,
    ),
    S(
        "terralith:bryce_canyon",
        "Bryce hoodoos (T2/D0) — badlands/canyon ONLY.",
        ["hot", "desert", "mesa"],
        badlands_terr(),
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "terralith:caldera",
        "Caldera bowl (T0.45/D0.8) — volcano_pipe ONLY (crater/caldera family).",
        ["volcanic", "temperate", "wet"],
        {"volcano_pipe": 1.0},
        slope=True,
    ),
    S(
        "terralith:cloud_forest",
        "Misty cloud forest (T0.25/D0.8) — wet hills, cool.",
        ["cold", "wet", "temperate"],
        {"hills_1": 1.0, "hills_2": 0.8, "dales": 0.55, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "terralith:cold_shrubland",
        "Cold dry shrubland (T0.14/D0) — cold steppe/plains.",
        ["cold"],
        {"steppe": 1.0, "plains": 0.7, "island_flats": 0.4},
        slope=False,
    ),
    S(
        "terralith:desert_canyon",
        "Desert canyon (T2/D0) — badlands + desert_canyon subs.",
        ["hot", "desert", "mesa"],
        badlands_terr(),
        slope=True,
        subterrains={"desert_canyon": 0.8, "canyon": 0.5},
    ),
    S(
        "terralith:desert_oasis",
        "Oasis in desert (T2/D0) — desert flats with river/dales wet pocket.",
        ["hot", "desert"],
        {"plains": 1.0, "dales": 0.7, "steppe": 0.55, "river": 0.45, "island_flats": 0.35},
        slope=False,
        subterrains={"river_bank": 0.4},
    ),
    S(
        "terralith:desert_spires",
        "Desert spires (T2/D0) — desert steppe + light badlands spikes.",
        ["hot", "desert"],
        {"steppe": 1.0, "plains": 0.55, "badlands": 0.45, "island_flats": 0.35},
        slope=True,
        subterrains={"desert_canyon": 0.35},
    ),
    S(
        "terralith:emerald_peaks",
        "Emerald peaks (T0.1/D0.4) — full mountain + peak subs.",
        ["cold", "alpine", "snowy"],
        mountains_full(),
        slope=True,
        subterrains=peak_subs(),
    ),
    S(
        "terralith:forested_highlands",
        "Forested highlands (T0.36/D0.2) — hills/plateau like highlands, temperate.",
        ["temperate", "cold"],
        hills_plateau(1.0, 0.85, 0.8, 0.5, 0.4),
        slope=True,
    ),
    S(
        "terralith:fractured_savanna",
        "Fractured savanna (T1.1/D0) — hot steppe + broken hills.",
        ["hot"],
        {"steppe": 1.0, "hills_1": 0.7, "plains": 0.55, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "terralith:frozen_cliffs",
        "Frozen cliffs (T0/D0.5) — snowy cliff mountains.",
        ["snowy", "cold", "alpine"],
        cliff_mount(),
        slope=True,
        subterrains={"bare_mountain": 0.7, "mountain_body": 0.45},
    ),
    S(
        "terralith:glacial_chasm",
        "Glacial chasm (T0/D0.5) — deep snowy canyon/mountains.",
        ["snowy", "cold", "alpine"],
        {
            "mountains_1": 1.0,
            "mountains_2": 0.9,
            "mountains_ridge_1": 0.75,
            "dolomites": 0.55,
            "island_mountains": 0.45,
        },
        slope=True,
        subterrains={"canyon": 0.55, "bare_mountain": 0.5, "mountain_body": 0.4},
    ),
    S(
        "terralith:granite_cliffs",
        "Granite cliffs (T0.4/D0.3) — temperate cliff ridges.",
        ["temperate"],
        cliff_mount(),
        slope=True,
        subterrains={"bare_mountain": 0.6, "mountain_body": 0.45},
    ),
    S(
        "terralith:gravel_beach",
        "Gravel beach (T0.8/D0.4) — beach ONLY.",
        ["temperate"],
        {"beach": 1.0},
        slope=False,
        subterrains={"ocean_beach": 0.7, "sea_beach": 0.4},
    ),
    S(
        "terralith:gravel_desert",
        "Cold gravel desert (T0.14/D0.5) — cold barren steppe/plains.",
        ["cold", "desert"],
        desert_flat(),
        slope=False,
    ),
    S(
        "terralith:haze_mountain",
        "Hazy mountain (T0.3/D0.6) — mountains with wet temperate feel.",
        ["temperate", "wet", "alpine"],
        mountains_full(),
        slope=True,
        subterrains=mountain_subs(),
    ),
    S(
        "terralith:highlands",
        "Classic highlands (T0.4/D0.4) — hills+plateau, not mountains.",
        ["temperate"],
        hills_plateau(),
        slope=True,
    ),
    S(
        "terralith:hot_shrubland",
        "Hot shrubland (T0.8/D0.4) — warm steppe/plains.",
        ["hot"],
        {"steppe": 1.0, "plains": 0.75, "hills_1": 0.4, "island_flats": 0.4},
        slope=False,
    ),
    S(
        "terralith:ice_marsh",
        "Ice marsh (T0.14/D0.9) — cold wet swamp dales.",
        ["cold", "snowy", "wet"],
        {"dales": 1.0, "plains": 0.55, "island_flats": 0.35},
        slope=False,
    ),
    S(
        "terralith:jungle_mountains",
        "Jungle mountains (T0.95/D0.9) — mountains + jungle climate.",
        ["hot", "jungle", "wet", "alpine"],
        mountains_full(),
        slope=True,
        subterrains=mountain_subs(),
    ),
    S(
        "terralith:lavender_forest",
        "Lavender forest (T0.7/D0.8) — temperate wet forest hills/dales.",
        ["temperate", "wet"],
        {"dales": 1.0, "hills_1": 0.7, "plains": 0.55, "island_hills": 0.4},
        slope=True,
    ),
    S(
        "terralith:lavender_valley",
        "Lavender valley (T0.7/D0.8) — valley plains/dales.",
        ["temperate", "wet"],
        plains_dales(1.0, 0.95, 0.4),
        slope=False,
    ),
    S(
        "terralith:lush_desert",
        "Lush desert (T2/D0) — desert flats with slight dales fertility.",
        ["hot", "desert"],
        {"steppe": 1.0, "plains": 0.8, "dales": 0.4, "island_flats": 0.4},
        slope=False,
    ),
    S(
        "terralith:lush_valley",
        "Lush valley (T0.4/D0.8) — wet temperate valley.",
        ["temperate", "wet"],
        plains_dales(1.0, 0.95, 0.45),
        slope=False,
    ),
    S(
        "terralith:mirage_isles",
        "Mirage isles (T0.7/D0.8) — fantasy floating islands.",
        ["temperate", "wet"],
        island_float(),
        slope=True,
    ),
    S(
        "terralith:moonlight_grove",
        "Moonlight grove (T0.7/D0.8) — mystical grove hills.",
        ["temperate", "wet"],
        {"hills_1": 1.0, "dales": 0.75, "plains": 0.45, "island_hills": 0.5},
        slope=True,
    ),
    S(
        "terralith:moonlight_valley",
        "Moonlight valley (T0.7/D0.8) — mystical valley floor.",
        ["temperate", "wet"],
        plains_dales(1.0, 0.9, 0.45),
        slope=False,
    ),
    S(
        "terralith:mountain_steppe",
        "Mountain steppe (T0.40/D0.45) — steppe foothills, light mountains fringe.",
        ["temperate", "alpine"],
        {
            "steppe": 1.0,
            "hills_1": 0.75,
            "hills_2": 0.55,
            "plateau": 0.5,
            "mountains_1": 0.35,
            "island_flats": 0.35,
        },
        slope=True,
        subterrains={"mountain_foothill": 0.45},
    ),
    S(
        "terralith:orchid_swamp",
        "Orchid swamp (T0.8/D0.9) — wet swamp dales.",
        ["hot", "wet", "jungle"],
        {"dales": 1.0, "plains": 0.55, "island_flats": 0.35},
        slope=False,
    ),
    S(
        "terralith:painted_mountains",
        "Painted mountains (T1/D0.3) — colorful full mountains, hot/mesa tint.",
        ["hot", "mesa", "alpine"],
        mountains_full(),
        slope=True,
        subterrains=peak_subs(),
    ),
    S(
        "terralith:red_oasis",
        "Red oasis (T2/D0) — desert oasis pocket.",
        ["hot", "desert"],
        {"plains": 1.0, "dales": 0.65, "steppe": 0.5, "river": 0.4, "island_flats": 0.35},
        slope=False,
        subterrains={"river_bank": 0.35},
    ),
    S(
        "terralith:rocky_jungle",
        "Rocky jungle (T0.95/D0.9) — jungle hills/rocky foothills.",
        ["hot", "jungle", "wet"],
        {"hills_1": 1.0, "hills_2": 0.75, "plains": 0.55, "dales": 0.5, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "terralith:rocky_mountains",
        "Rocky mountains (T0.3/D0.3) — full mountains.",
        ["temperate", "alpine", "cold"],
        mountains_full(),
        slope=True,
        subterrains=mountain_subs(),
    ),
    S(
        "terralith:rocky_shrubland",
        "Rocky shrubland (T0.14/D0) — cold rocky steppe/hills.",
        ["cold"],
        {"steppe": 1.0, "hills_1": 0.7, "plains": 0.45, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "terralith:sakura_grove",
        "Sakura grove (T0.7/D0.8) — temperate grove hills.",
        ["temperate", "wet"],
        {"hills_1": 1.0, "dales": 0.7, "plains": 0.5, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "terralith:sakura_valley",
        "Sakura valley (T0.7/D0.8) — temperate valley.",
        ["temperate", "wet"],
        plains_dales(1.0, 0.9, 0.4),
        slope=False,
    ),
    S(
        "terralith:sandstone_valley",
        "Sandstone valley (T2/D0) — desert valley flats + light canyon.",
        ["hot", "desert"],
        {"steppe": 1.0, "plains": 0.75, "badlands": 0.35, "island_flats": 0.4},
        slope=False,
        subterrains={"desert_canyon": 0.3},
    ),
    S(
        "terralith:savanna_badlands",
        "Savanna badlands (T1/D0) — hot badlands/mesa.",
        ["hot", "mesa"],
        badlands_terr(),
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "terralith:savanna_slopes",
        "Savanna slopes (T1/D0) — hot hills/steppe slopes.",
        ["hot"],
        {"hills_1": 1.0, "hills_2": 0.8, "steppe": 0.7, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "terralith:scarlet_mountains",
        "Scarlet mountains (T0.1/D0.4) — cold alpine mountains.",
        ["cold", "snowy", "alpine"],
        mountains_full(),
        slope=True,
        subterrains=peak_subs(),
    ),
    S(
        "terralith:shield_clearing",
        "Shield clearing (T0.4/D-0.5) — open shield plains.",
        ["temperate", "cold"],
        plains_dales(1.0, 0.55, 0.4, w_s=0.45),
        slope=False,
    ),
    S(
        "terralith:shield",
        "Canadian shield (T0.4/D0.8) — rocky wet hills/dales.",
        ["temperate", "cold", "wet"],
        {"hills_1": 1.0, "dales": 0.85, "plains": 0.5, "island_hills": 0.4},
        slope=True,
    ),
    S(
        "terralith:shrubland",
        "Shrubland (T1.2/D0) — hot scrub steppe.",
        ["hot"],
        {"steppe": 1.0, "plains": 0.7, "island_flats": 0.4},
        slope=False,
    ),
    S(
        "terralith:siberian_grove",
        "Siberian grove (T0.23/D0.8) — cold wet grove hills.",
        ["cold", "wet"],
        {"hills_1": 1.0, "dales": 0.7, "plains": 0.4, "island_hills": 0.4},
        slope=True,
    ),
    S(
        "terralith:siberian_taiga",
        "Siberian taiga (T0.3/D1.2) — cold wet taiga dales/hills.",
        ["cold", "wet"],
        {"dales": 1.0, "hills_1": 0.75, "plains": 0.4, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "terralith:skylands",
        "Skylands base (T0.5/D0.5) — floating island kit.",
        ["temperate"],
        island_float(),
        slope=True,
    ),
    S(
        "terralith:skylands_autumn",
        "Skylands autumn (T0.5/D0.5) — floating islands.",
        ["temperate"],
        island_float(),
        slope=True,
    ),
    S(
        "terralith:skylands_spring",
        "Skylands spring (T0.5/D0.5) — floating islands.",
        ["temperate", "wet"],
        island_float(),
        slope=True,
    ),
    S(
        "terralith:skylands_summer",
        "Skylands summer (T0.5/D0.5) — floating islands.",
        ["temperate", "hot"],
        island_float(),
        slope=True,
    ),
    S(
        "terralith:skylands_winter",
        "Skylands winter (T0.2/D0.5) — snowy floating islands.",
        ["cold", "snowy"],
        island_float(),
        slope=True,
    ),
    S(
        "terralith:snowy_badlands",
        "Snowy badlands (T0/D0.5) — cold mesa/badlands.",
        ["snowy", "cold", "mesa"],
        badlands_terr(),
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "terralith:snowy_cherry_grove",
        "Snowy cherry grove (T0.1/D0.8) — snowy grove hills.",
        ["snowy", "cold"],
        {"hills_1": 1.0, "dales": 0.7, "plains": 0.4, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "terralith:snowy_maple_forest",
        "Snowy maple forest (T0.1/D0.2) — cold forest hills.",
        ["snowy", "cold"],
        {"hills_1": 1.0, "dales": 0.75, "plains": 0.4, "island_hills": 0.4},
        slope=True,
    ),
    S(
        "terralith:snowy_shield",
        "Snowy shield (T0.1/D0.8) — snowy rocky hills.",
        ["snowy", "cold", "wet"],
        {"hills_1": 1.0, "dales": 0.8, "plains": 0.4, "island_hills": 0.4},
        slope=True,
    ),
    S(
        "terralith:steppe",
        "Steppe (T0.4/D-0.5) — steppe primary.",
        ["temperate"],
        {"steppe": 1.0, "plains": 0.55, "island_flats": 0.4},
        slope=False,
    ),
    S(
        "terralith:stony_spires",
        "Stony spires (T0.7/D0.3) — rocky mountains/spires.",
        ["temperate", "alpine"],
        {
            "mountains_1": 1.0,
            "mountains_2": 0.85,
            "mountains_ridge_1": 0.75,
            "dolomites": 0.65,
            "island_mountains": 0.5,
        },
        slope=True,
        subterrains={"bare_mountain": 0.65, "mountain_body": 0.45},
    ),
    S(
        "terralith:temperate_highlands",
        "Temperate highlands (T0.9/D0.2) — warm hills/plateau (not mountains).",
        ["temperate", "hot"],
        hills_plateau(1.0, 0.9, 0.85, 0.5, 0.45),
        slope=True,
    ),
    S(
        "terralith:tropical_jungle",
        "Tropical jungle (T0.95/D0.9) — jungle plains/dales/hills.",
        ["hot", "jungle", "wet"],
        jungle_low(),
        slope=True,
    ),
    S(
        "terralith:valley_clearing",
        "Valley clearing (T0.4/D-0.5) — open valley plains.",
        ["temperate"],
        plains_dales(1.0, 0.7, 0.4, w_s=0.35),
        slope=False,
    ),
    S(
        "terralith:volcanic_crater",
        "Volcanic crater (T1/D0.3) — volcano_pipe ONLY.",
        ["volcanic", "hot"],
        {"volcano_pipe": 1.0},
        slope=True,
    ),
    S(
        "terralith:volcanic_peaks",
        "Volcanic peaks (T1/D0.3) — volcano + island_volcano ONLY (no pipe/badlands).",
        ["volcanic", "hot", "alpine"],
        {"volcano": 1.0, "island_volcano": 1.0},
        slope=True,
    ),
    S(
        "terralith:warm_river",
        "Warm river (T0.5/D0.5) — river primary.",
        ["temperate", "hot"],
        {"river": 1.0},
        slope=False,
        subterrains={"river_bank": 1.0},
    ),
    S(
        "terralith:warped_mesa",
        "Warped mesa (T2/D0) — desert mesa/badlands.",
        ["hot", "desert", "mesa"],
        badlands_terr(),
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "terralith:white_cliffs",
        "White cliffs (T0.4/D0.3) — chalky cliff ridges.",
        ["temperate"],
        cliff_mount(),
        slope=True,
        subterrains={"bare_mountain": 0.65, "mountain_body": 0.4, "ocean_beach": 0.25},
    ),
    S(
        "terralith:white_mesa",
        "White mesa (T2/D0) — desert mesa/badlands.",
        ["hot", "desert", "mesa"],
        badlands_terr(),
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "terralith:windswept_spires",
        "Windswept spires (T0.2/D0.3) — cold rocky ridges.",
        ["cold", "alpine"],
        {
            "mountains_1": 1.0,
            "mountains_ridge_1": 0.85,
            "mountains_2": 0.7,
            "dolomites": 0.55,
            "island_mountains": 0.45,
        },
        slope=True,
        subterrains={"bare_mountain": 0.7, "mountain_body": 0.4},
    ),
    S(
        "terralith:wintry_forest",
        "Wintry forest (T-0.5/D0.4) — snowy forest hills.",
        ["snowy", "cold"],
        {"hills_1": 1.0, "dales": 0.8, "plains": 0.35, "island_hills": 0.4},
        slope=True,
    ),
    S(
        "terralith:wintry_lowlands",
        "Wintry lowlands (T-0.5/D0.4) — snowy plains/dales.",
        ["snowy", "cold"],
        plains_dales(1.0, 0.85, 0.4),
        slope=False,
    ),
    S(
        "terralith:yellowstone",
        "Yellowstone (T0.25/D0.8) — geothermal plateau/hills with wet climate; not volcano-ring-only.",
        ["temperate", "wet", "volcanic"],
        {"hills_1": 1.0, "hills_2": 0.7, "dales": 0.65, "plateau": 0.55, "island_hills": 0.4, "island_plateau": 0.35},
        slope=True,
    ),
    S(
        "terralith:yosemite_cliffs",
        "Yosemite cliffs (T0.375/D0.8) — granite cliff mountains, wet.",
        ["temperate", "wet", "alpine"],
        cliff_mount(),
        slope=True,
        subterrains={"bare_mountain": 0.7, "mountain_body": 0.5},
    ),
    S(
        "terralith:yosemite_lowlands",
        "Yosemite lowlands (T0.25/D0.8) — valley floor under cliffs.",
        ["temperate", "wet"],
        plains_dales(1.0, 0.85, 0.4),
        slope=False,
    ),
    # --- Vanilla (1.18.2 + common later IDs kept for forward defaults) ---
    S(
        "minecraft:plains",
        "Vanilla plains.",
        ["temperate"],
        plains_dales(1.0, 0.55, 0.5),
        slope=False,
    ),
    S(
        "minecraft:sunflower_plains",
        "Sunflower plains.",
        ["temperate"],
        plains_dales(1.0, 0.5, 0.45),
        slope=False,
    ),
    S(
        "minecraft:snowy_plains",
        "Snowy plains / tundra.",
        ["snowy", "cold"],
        plains_dales(1.0, 0.45, 0.4),
        slope=False,
    ),
    S(
        "minecraft:forest",
        "Temperate forest.",
        ["temperate"],
        {"dales": 1.0, "hills_1": 0.55, "plains": 0.5, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "minecraft:flower_forest",
        "Flower forest.",
        ["temperate"],
        {"dales": 1.0, "hills_1": 0.6, "plains": 0.55, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "minecraft:birch_forest",
        "Birch forest.",
        ["temperate"],
        {"dales": 1.0, "hills_1": 0.5, "plains": 0.5, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "minecraft:old_growth_birch_forest",
        "Old growth birch.",
        ["temperate"],
        {"dales": 1.0, "hills_1": 0.55, "plains": 0.45, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "minecraft:dark_forest",
        "Dark forest.",
        ["temperate"],
        {"dales": 1.0, "hills_1": 0.45, "plains": 0.4, "island_hills": 0.3},
        slope=True,
    ),
    S(
        "minecraft:taiga",
        "Taiga.",
        ["cold", "temperate"],
        {"dales": 1.0, "hills_1": 0.65, "plains": 0.4, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "minecraft:snowy_taiga",
        "Snowy taiga.",
        ["snowy", "cold"],
        {"dales": 1.0, "hills_1": 0.7, "plains": 0.35, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "minecraft:old_growth_pine_taiga",
        "Old growth pine taiga.",
        ["cold", "temperate"],
        {"dales": 1.0, "hills_1": 0.7, "plains": 0.35, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "minecraft:old_growth_spruce_taiga",
        "Old growth spruce taiga.",
        ["cold"],
        {"dales": 1.0, "hills_1": 0.7, "plains": 0.35, "island_hills": 0.35},
        slope=True,
    ),
    S(
        "minecraft:desert",
        "Desert.",
        ["hot", "desert"],
        desert_flat(),
        slope=False,
    ),
    S(
        "minecraft:badlands",
        "Badlands.",
        ["hot", "desert", "mesa"],
        badlands_terr(),
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "minecraft:eroded_badlands",
        "Eroded badlands.",
        ["hot", "desert", "mesa"],
        badlands_terr(),
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "minecraft:wooded_badlands",
        "Wooded badlands.",
        ["hot", "desert", "mesa"],
        {"badlands": 1.0, "hills_1": 0.4},
        slope=True,
        subterrains=badlands_subs(),
    ),
    S(
        "minecraft:jungle",
        "Jungle.",
        ["hot", "jungle", "wet"],
        jungle_low(),
        slope=True,
    ),
    S(
        "minecraft:sparse_jungle",
        "Sparse jungle.",
        ["hot", "jungle"],
        {"plains": 1.0, "dales": 0.6, "hills_1": 0.45, "island_flats": 0.4},
        slope=True,
    ),
    S(
        "minecraft:bamboo_jungle",
        "Bamboo jungle.",
        ["hot", "jungle", "wet"],
        jungle_low(),
        slope=True,
    ),
    S(
        "minecraft:swamp",
        "Swamp.",
        ["temperate", "wet"],
        {"dales": 1.0, "plains": 0.5, "island_flats": 0.35},
        slope=False,
    ),
    S(
        "minecraft:mangrove_swamp",
        "Mangrove swamp.",
        ["hot", "wet", "jungle"],
        {"dales": 1.0, "plains": 0.45, "island_flats": 0.4},
        slope=False,
    ),
    S(
        "minecraft:beach",
        "Beach.",
        ["temperate"],
        {"beach": 1.0},
        slope=False,
        subterrains={"ocean_beach": 0.7, "sea_beach": 0.4},
    ),
    S(
        "minecraft:snowy_beach",
        "Snowy beach.",
        ["snowy", "cold"],
        {"beach": 1.0},
        slope=False,
        subterrains={"ocean_beach": 0.7, "sea_beach": 0.35},
    ),
    S(
        "minecraft:stony_shore",
        "Stony shore.",
        ["temperate", "cold"],
        {"beach": 1.0, "hills_1": 0.35},
        slope=True,
        subterrains={"ocean_beach": 0.6, "sea_beach": 0.5},
    ),
    S(
        "minecraft:river",
        "River.",
        ["temperate"],
        {"river": 1.0},
        slope=False,
        subterrains={"river_bank": 1.0},
    ),
    S(
        "minecraft:frozen_river",
        "Frozen river.",
        ["snowy", "cold"],
        {"river": 1.0},
        slope=False,
        subterrains={"river_bank": 1.0},
    ),
    S(
        "minecraft:windswept_hills",
        "Windswept hills (ex-mountains).",
        ["temperate", "cold", "alpine"],
        {"hills_1": 1.0, "hills_2": 0.9, "mountains_1": 0.55, "island_hills": 0.5},
        slope=True,
        subterrains={"mountain_foothill": 0.4},
    ),
    S(
        "minecraft:windswept_forest",
        "Windswept forest.",
        ["temperate", "cold"],
        {"hills_1": 1.0, "hills_2": 0.8, "dales": 0.5, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "minecraft:windswept_gravelly_hills",
        "Windswept gravelly hills.",
        ["temperate", "cold", "alpine"],
        {"hills_1": 1.0, "hills_2": 0.85, "mountains_1": 0.45, "island_hills": 0.45},
        slope=True,
        subterrains={"bare_mountain": 0.35},
    ),
    S(
        "minecraft:windswept_savanna",
        "Windswept savanna.",
        ["hot"],
        {"hills_1": 1.0, "steppe": 0.75, "plains": 0.45, "island_hills": 0.4},
        slope=True,
    ),
    S(
        "minecraft:savanna",
        "Savanna.",
        ["hot"],
        {"steppe": 1.0, "plains": 0.7, "island_flats": 0.4},
        slope=False,
    ),
    S(
        "minecraft:savanna_plateau",
        "Savanna plateau.",
        ["hot"],
        {"plateau": 1.0, "steppe": 0.7, "hills_1": 0.45, "island_plateau": 0.5},
        slope=True,
    ),
    S(
        "minecraft:meadow",
        "Meadow.",
        ["temperate", "alpine"],
        {"hills_1": 1.0, "plains": 0.7, "plateau": 0.55, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "minecraft:grove",
        "Snowy grove.",
        ["snowy", "cold", "alpine"],
        {"hills_1": 1.0, "hills_2": 0.7, "dales": 0.45, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "minecraft:cherry_grove",
        "Cherry grove (forward default).",
        ["temperate"],
        {"hills_1": 1.0, "dales": 0.7, "plains": 0.5, "island_hills": 0.45},
        slope=True,
    ),
    S(
        "minecraft:snowy_slopes",
        "Snowy slopes.",
        ["snowy", "cold", "alpine"],
        {"hills_1": 1.0, "hills_2": 0.85, "mountains_1": 0.55, "island_hills": 0.45},
        slope=True,
        subterrains={"mountain_foothill": 0.5, "bare_mountain": 0.35},
    ),
    S(
        "minecraft:jagged_peaks",
        "Jagged peaks.",
        ["snowy", "cold", "alpine"],
        mountains_full(),
        slope=True,
        subterrains=peak_subs(),
    ),
    S(
        "minecraft:frozen_peaks",
        "Frozen peaks.",
        ["snowy", "cold", "alpine"],
        mountains_full(),
        slope=True,
        subterrains=peak_subs(),
    ),
    S(
        "minecraft:stony_peaks",
        "Stony peaks.",
        ["temperate", "alpine"],
        mountains_full(),
        slope=True,
        subterrains=peak_subs(),
    ),
    S(
        "minecraft:ice_spikes",
        "Ice spikes.",
        ["snowy", "cold"],
        {"plains": 1.0, "dales": 0.4, "island_flats": 0.35},
        slope=False,
    ),
    S(
        "minecraft:mushroom_fields",
        "Mushroom fields.",
        ["temperate", "wet"],
        {"plains": 1.0, "island_flats": 0.85, "dales": 0.4},
        slope=False,
    ),
]


# ===========================================================================
# B) CAVE CATALOG — explicit Cond + climates (from cave-biomes.toml themes).
# ===========================================================================

def pulse(
    *,
    cond_m: float = -10.0,
    cond_t: float = -10.0,
    cond_f: float = -10.0,
    glob_m: float = 0.0,
    glob_t: float = 0.0,
    glob_f: float = 0.0,
    loc_m: float = 0.0,
    loc_t: float = 0.0,
    loc_f: float = 0.0,
    falloff: float = 1.0,
) -> dict[str, Any]:
    return {
        "conditions": {"moisture": cond_m, "temperature": cond_t, "fertility": cond_f},
        "global": {"moisture": glob_m, "temperature": glob_t, "fertility": glob_f},
        "local": {
            "moisture": loc_m,
            "temperature": loc_t,
            "fertility": loc_f,
            "falloff_per_hop": falloff,
        },
    }


def C(
    biome: str,
    note: str,
    *,
    generation_type: str,
    placement_type: str,
    climates: list[str],
    temperature: float,
    vegetation_density: float,
    weight: float,
    cond_temp: int,
    delta_temp: int,
    cond_humidity: int,
    delta_humidity: int,
    cond_fertility: int,
    delta_fertility: int,
    stat_generator: bool = False,
    stats: dict[str, Any] | None = None,
    ceiling_patch_min: float | None = None,
    ceiling_patch_max: float | None = None,
    island_max_radius: float | None = None,
) -> dict[str, Any]:
    body: dict[str, Any] = {
        "_note": note,
        "biome": biome,
        "generation_type": generation_type,
        "placement_type": placement_type,
        "climates": list(climates),
        "systems": [],
        "dimension": "overworld",
        "temperature": temperature,
        "vegetation_density": vegetation_density,
        "weight": weight,
        "stat_generator": stat_generator,
        "auto_generated": False,
        "cond_temp": cond_temp,
        "delta_temp": delta_temp,
        "cond_humidity": cond_humidity,
        "delta_humidity": delta_humidity,
        "cond_fertility": cond_fertility,
        "delta_fertility": delta_fertility,
        "stats": stats if stats is not None else pulse(),
    }
    if ceiling_patch_min is not None:
        body["ceiling_patch_min"] = ceiling_patch_min
    if ceiling_patch_max is not None:
        body["ceiling_patch_max"] = ceiling_patch_max
    if island_max_radius is not None:
        body["island_max_radius"] = island_max_radius
    return body


CAVES: list[dict[str, Any]] = [
    C(
        "newterraforged:cave_thermal_springs",
        "Hot wet geothermal springs generator.",
        generation_type="primary",
        placement_type="full_region",
        climates=["hot", "wet"],
        temperature=0.90,
        vegetation_density=0.15,
        weight=1.0,
        cond_temp=95,
        delta_temp=25,
        cond_humidity=70,
        delta_humidity=20,
        cond_fertility=80,
        delta_fertility=25,
        stat_generator=True,
        stats=pulse(cond_t=2, cond_m=1, loc_t=3, loc_m=4, loc_f=4, falloff=0.9),
    ),
    C(
        "terralith:cave/frostfire_caves",
        "Cold deep blue-fire + ice + sculk; frost generator.",
        generation_type="primary",
        placement_type="full_region",
        climates=["frost"],
        temperature=0.05,
        vegetation_density=0.10,
        weight=1.0,
        cond_temp=-25,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=20,
        delta_fertility=20,
        stat_generator=True,
        stats=pulse(
            cond_t=-2,
            glob_t=-4,
            glob_m=-1,
            glob_f=-2,
            loc_t=-3,
            loc_m=-1,
            falloff=1.0,
        ),
    ),
    C(
        "terralith:cave/mantle_caves",
        "Earth's mantle lava deep — volcanic/hot generator.",
        generation_type="primary",
        placement_type="full_region",
        climates=["volcanic", "hot"],
        temperature=0.88,
        vegetation_density=0.10,
        weight=0.9,
        cond_temp=125,
        delta_temp=25,
        cond_humidity=10,
        delta_humidity=15,
        cond_fertility=15,
        delta_fertility=20,
        stat_generator=True,
        stats=pulse(
            cond_t=4,
            glob_t=3,
            glob_m=-2,
            glob_f=-1,
            loc_t=2,
            loc_m=-1,
            falloff=1.0,
        ),
    ),
    C(
        "terralith:cave/fungal_caves",
        "Mushrooms + moss — wet/normal high fertility.",
        generation_type="primary",
        placement_type="full_region",
        climates=["wet", "normal"],
        temperature=0.55,
        vegetation_density=0.85,
        weight=1.0,
        cond_temp=45,
        delta_temp=20,
        cond_humidity=75,
        delta_humidity=15,
        cond_fertility=145,
        delta_fertility=30,
        stats=pulse(cond_m=1, cond_f=2, glob_m=3, glob_f=2, loc_m=2, loc_f=1, falloff=0.85),
    ),
    C(
        "terralith:cave/ice_caves",
        "Cold ice caves transition.",
        generation_type="transition",
        placement_type="full_region",
        climates=["frost"],
        temperature=0.08,
        vegetation_density=0.08,
        weight=0.65,
        cond_temp=-30,
        delta_temp=20,
        cond_humidity=45,
        delta_humidity=15,
        cond_fertility=15,
        delta_fertility=15,
        stats=pulse(
            cond_t=-2,
            glob_m=2,
            glob_t=-4,
            glob_f=-1,
            loc_m=1,
            loc_t=-2,
            falloff=1.0,
        ),
    ),
    C(
        "terralith:cave/thermal_caves",
        "Geothermal wet magma transition (generator-ish).",
        generation_type="transition",
        placement_type="full_region",
        climates=["hot", "wet"],
        temperature=0.78,
        vegetation_density=0.35,
        weight=0.85,
        cond_temp=90,
        delta_temp=20,
        cond_humidity=70,
        delta_humidity=20,
        cond_fertility=75,
        delta_fertility=25,
        stats=pulse(cond_m=1, cond_t=2, glob_m=1, glob_t=2, loc_t=1, falloff=1.0),
    ),
    C(
        "terralith:cave/desert_caves",
        "Hot dry sandy caves.",
        generation_type="transition",
        placement_type="full_region",
        climates=["dry", "hot"],
        temperature=0.82,
        vegetation_density=0.05,
        weight=0.75,
        cond_temp=80,
        delta_temp=20,
        cond_humidity=15,
        delta_humidity=15,
        cond_fertility=20,
        delta_fertility=20,
        stats=pulse(
            cond_m=-2,
            cond_t=1,
            glob_m=-3,
            glob_t=2,
            glob_f=-2,
            loc_m=-2,
            loc_t=1,
            loc_f=-1,
            falloff=1.0,
        ),
    ),
    C(
        "terralith:cave/crystal_caves",
        "Glowing crystals — island_patch special.",
        generation_type="special",
        placement_type="island_patch",
        climates=["normal"],
        temperature=0.42,
        vegetation_density=0.35,
        weight=0.85,
        cond_temp=35,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=35,
        delta_fertility=20,
        island_max_radius=2.8,
        stats=pulse(cond_f=-2, glob_t=-1, glob_f=-3, loc_f=-1, falloff=1.2),
    ),
    C(
        "terralith:cave/deep_caves",
        "Barren deep stone.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.15,
        vegetation_density=0.12,
        weight=0.9,
        cond_temp=20,
        delta_temp=20,
        cond_humidity=35,
        delta_humidity=15,
        cond_fertility=30,
        delta_fertility=20,
        stats=pulse(
            glob_m=-1,
            glob_t=-1,
            glob_f=-2,
            loc_m=-1,
            loc_t=-1,
            loc_f=-1,
            falloff=1.0,
        ),
    ),
    C(
        "terralith:cave/andesite_caves",
        "Barren andesite stone.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.50,
        vegetation_density=0.08,
        weight=0.7,
        cond_temp=30,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=35,
        delta_fertility=20,
        stats=pulse(glob_m=-1, glob_f=-2, loc_m=-1, loc_f=-1, falloff=1.1),
    ),
    C(
        "terralith:cave/diorite_caves",
        "Barren diorite stone.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.48,
        vegetation_density=0.08,
        weight=0.7,
        cond_temp=30,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=35,
        delta_fertility=20,
        stats=pulse(glob_m=-1, glob_f=-2, loc_m=-1, loc_f=-1, falloff=1.1),
    ),
    C(
        "terralith:cave/granite_caves",
        "Barren granite stone.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.52,
        vegetation_density=0.08,
        weight=0.7,
        cond_temp=32,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=35,
        delta_fertility=20,
        stats=pulse(glob_m=-1, glob_f=-2, loc_m=-1, loc_f=-1, falloff=1.1),
    ),
    C(
        "terralith:cave/tuff_caves",
        "Barren tuff stone.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.46,
        vegetation_density=0.08,
        weight=0.7,
        cond_temp=30,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=35,
        delta_fertility=20,
        stats=pulse(glob_m=-1, glob_f=-2, loc_m=-1, loc_f=-1, falloff=1.1),
    ),
    C(
        "terralith:cave/infested_caves",
        "Infested barren stone.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.40,
        vegetation_density=0.15,
        weight=0.8,
        cond_temp=28,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=30,
        delta_fertility=20,
        stats=pulse(glob_m=-1, glob_f=-2, loc_m=-1, loc_f=-1, falloff=1.1),
    ),
    C(
        "terralith:cave/underground_jungle",
        "Blacklisted for mega/giga gen but keep jungle Cond for non-blacklist use.",
        generation_type="primary",
        placement_type="full_region",
        climates=["wet", "hot"],
        temperature=0.70,
        vegetation_density=0.90,
        weight=0.5,
        cond_temp=55,
        delta_temp=20,
        cond_humidity=85,
        delta_humidity=15,
        cond_fertility=150,
        delta_fertility=30,
        stats=pulse(cond_m=2, cond_f=2, glob_m=3, glob_f=3, loc_m=2, loc_f=2, falloff=0.85),
    ),
    C(
        "terralith:cave/steaming_jungle",
        "Blacklisted steaming jungle — hot wet jungle Cond for passport completeness.",
        generation_type="primary",
        placement_type="full_region",
        climates=["wet", "hot"],
        temperature=0.75,
        vegetation_density=0.85,
        weight=0.5,
        cond_temp=75,
        delta_temp=20,
        cond_humidity=80,
        delta_humidity=15,
        cond_fertility=110,
        delta_fertility=25,
        stats=pulse(cond_m=2, cond_t=1, glob_m=3, glob_t=1, glob_f=2, loc_m=2, loc_f=1, falloff=0.85),
    ),
    C(
        "biomesoplenty:glowing_grotto",
        "Lush glowing grotto — wet high fertility.",
        generation_type="primary",
        placement_type="full_region",
        climates=["wet", "normal"],
        temperature=0.62,
        vegetation_density=0.80,
        weight=0.9,
        cond_temp=40,
        delta_temp=20,
        cond_humidity=70,
        delta_humidity=15,
        cond_fertility=130,
        delta_fertility=30,
        stats=pulse(cond_m=1, cond_f=2, glob_m=3, glob_f=3, loc_m=2, loc_f=2, falloff=0.9),
    ),
    C(
        "byg:brimstone_caverns",
        "Volcanic brimstone generator.",
        generation_type="primary",
        placement_type="full_region",
        climates=["volcanic", "hot"],
        temperature=0.93,
        vegetation_density=0.05,
        weight=0.9,
        cond_temp=120,
        delta_temp=25,
        cond_humidity=15,
        delta_humidity=15,
        cond_fertility=20,
        delta_fertility=20,
        stat_generator=True,
        stats=pulse(
            cond_t=3,
            glob_t=4,
            glob_m=-2,
            glob_f=-1,
            loc_t=2,
            loc_m=-1,
            falloff=1.1,
        ),
    ),
    C(
        "byg:crimson_gardens",
        "Nether-adjacent hot wet fungal-ish (blacklisted but keep defaults).",
        generation_type="transition",
        placement_type="full_region",
        climates=["hot", "wet"],
        temperature=0.70,
        vegetation_density=0.75,
        weight=0.9,
        cond_temp=100,
        delta_temp=25,
        cond_humidity=55,
        delta_humidity=15,
        cond_fertility=90,
        delta_fertility=25,
        stats=pulse(cond_m=1, cond_f=2, glob_m=3, glob_f=2, loc_m=2, loc_f=1, falloff=0.85),
    ),
    C(
        "byg:shattered_glacier",
        "Extreme cold glacier.",
        generation_type="transition",
        placement_type="full_region",
        climates=["frost"],
        temperature=0.03,
        vegetation_density=0.08,
        weight=0.9,
        cond_temp=-40,
        delta_temp=15,
        cond_humidity=30,
        delta_humidity=15,
        cond_fertility=10,
        delta_fertility=15,
        stats=pulse(
            cond_t=-2,
            glob_m=1,
            glob_t=-4,
            glob_f=-1,
            loc_m=1,
            loc_t=-2,
            falloff=1.0,
        ),
    ),
    C(
        "byg:subzero_hypogeal",
        "Extreme subzero special.",
        generation_type="special",
        placement_type="full_region",
        climates=["frost"],
        temperature=0.02,
        vegetation_density=0.05,
        weight=0.6,
        cond_temp=-45,
        delta_temp=15,
        cond_humidity=25,
        delta_humidity=15,
        cond_fertility=8,
        delta_fertility=15,
        stats=pulse(
            cond_t=-3,
            glob_m=2,
            glob_t=-5,
            glob_f=-2,
            loc_m=1,
            loc_t=-3,
            falloff=1.0,
        ),
    ),
    C(
        "byg:nightshade_redwoods",
        "Cool forest-ish underground redwoods.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal", "wet"],
        temperature=0.35,
        vegetation_density=0.55,
        weight=0.8,
        cond_temp=15,
        delta_temp=20,
        cond_humidity=55,
        delta_humidity=15,
        cond_fertility=110,
        delta_fertility=25,
        stats=pulse(
            cond_t=-1,
            cond_f=2,
            glob_m=2,
            glob_t=-2,
            glob_f=2,
            loc_m=1,
            loc_f=1,
            falloff=0.95,
        ),
    ),
    C(
        "byg:quartz_desert",
        "Dry hot quartz desert caves.",
        generation_type="transition",
        placement_type="full_region",
        climates=["dry", "hot"],
        temperature=0.78,
        vegetation_density=0.05,
        weight=0.8,
        cond_temp=80,
        delta_temp=20,
        cond_humidity=15,
        delta_humidity=15,
        cond_fertility=20,
        delta_fertility=20,
        stats=pulse(
            cond_m=-2,
            cond_t=1,
            glob_m=-3,
            glob_t=2,
            glob_f=-2,
            loc_m=-2,
            loc_t=1,
            loc_f=-1,
            falloff=1.0,
        ),
    ),
    C(
        "byg:skyris_caves",
        "Crystal ceiling patch.",
        generation_type="special",
        placement_type="ceiling_patch",
        climates=["normal"],
        temperature=0.38,
        vegetation_density=0.55,
        weight=0.6,
        cond_temp=35,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=40,
        delta_fertility=20,
        ceiling_patch_min=0.25,
        ceiling_patch_max=0.50,
        stats=pulse(cond_f=-2, glob_t=-1, glob_f=-3, loc_f=-1, falloff=1.2),
    ),
    C(
        "regions_unexplored:bioshroom_caves",
        "Fungal wet bioshrooms.",
        generation_type="transition",
        placement_type="full_region",
        climates=["wet", "normal"],
        temperature=0.53,
        vegetation_density=0.80,
        weight=0.9,
        cond_temp=45,
        delta_temp=20,
        cond_humidity=75,
        delta_humidity=15,
        cond_fertility=140,
        delta_fertility=30,
        stats=pulse(cond_m=1, cond_f=2, glob_m=3, glob_f=2, loc_m=2, loc_f=1, falloff=0.85),
    ),
    C(
        "regions_unexplored:mycotoxic_undergrowth",
        "Toxic fungal wet undergrowth.",
        generation_type="transition",
        placement_type="full_region",
        climates=["wet", "normal"],
        temperature=0.48,
        vegetation_density=0.70,
        weight=0.8,
        cond_temp=45,
        delta_temp=20,
        cond_humidity=75,
        delta_humidity=15,
        cond_fertility=135,
        delta_fertility=30,
        stats=pulse(cond_m=1, cond_f=2, glob_m=3, glob_f=2, loc_m=2, loc_f=1, falloff=0.85),
    ),
    C(
        "regions_unexplored:ancient_delta",
        "Wet coastal/delta caves (toml coastal + transition; one curated coastal).",
        generation_type="coastal",
        placement_type="full_region",
        climates=["wet", "normal"],
        temperature=0.42,
        vegetation_density=0.55,
        weight=0.95,
        cond_temp=30,
        delta_temp=20,
        cond_humidity=85,
        delta_humidity=15,
        cond_fertility=100,
        delta_fertility=25,
        stats=pulse(
            cond_m=2,
            glob_m=4,
            glob_t=-1,
            glob_f=1,
            loc_m=2,
            loc_f=1,
            falloff=0.9,
        ),
    ),
    C(
        "regions_unexplored:redstone_caves",
        "Dryish redstone ceiling patch.",
        generation_type="special",
        placement_type="ceiling_patch",
        climates=["dry", "normal"],
        temperature=0.62,
        vegetation_density=0.10,
        weight=0.55,
        cond_temp=55,
        delta_temp=20,
        cond_humidity=30,
        delta_humidity=15,
        cond_fertility=40,
        delta_fertility=20,
        ceiling_patch_min=0.30,
        ceiling_patch_max=0.55,
        stats=pulse(
            cond_t=0,
            cond_f=-2,
            glob_m=-1,
            glob_t=2,
            glob_f=-3,
            loc_t=1,
            loc_f=-1,
            falloff=1.0,
        ),
    ),
    C(
        "regions_unexplored:prismachasm",
        "Crystal island_patch.",
        generation_type="special",
        placement_type="island_patch",
        climates=["normal"],
        temperature=0.50,
        vegetation_density=0.40,
        weight=0.85,
        cond_temp=35,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=40,
        delta_fertility=20,
        island_max_radius=2.5,
        stats=pulse(cond_f=-2, glob_t=-1, glob_f=-3, loc_f=-1, falloff=1.2),
    ),
    C(
        "minecraft:dripstone_caves",
        "Moist temperate dripstone coastal.",
        generation_type="coastal",
        placement_type="full_region",
        climates=["normal", "wet"],
        temperature=0.50,
        vegetation_density=0.40,
        weight=0.40,
        cond_temp=35,
        delta_temp=20,
        cond_humidity=60,
        delta_humidity=15,
        cond_fertility=50,
        delta_fertility=20,
        stats=pulse(cond_m=1, glob_m=2, glob_f=1, loc_m=1, loc_f=1, falloff=0.9),
    ),
    C(
        "wildnature:glowshroom_caves",
        "Glowshroom fungal wet primary.",
        generation_type="primary",
        placement_type="full_region",
        climates=["wet", "normal"],
        temperature=0.58,
        vegetation_density=0.85,
        weight=0.9,
        cond_temp=45,
        delta_temp=20,
        cond_humidity=75,
        delta_humidity=15,
        cond_fertility=140,
        delta_fertility=30,
        stats=pulse(cond_m=1, cond_f=2, glob_m=3, glob_f=2, loc_m=2, loc_f=1, falloff=0.85),
    ),
    C(
        "wildnature:icicle_caves",
        "Icicle frost caves.",
        generation_type="transition",
        placement_type="full_region",
        climates=["frost"],
        temperature=0.12,
        vegetation_density=0.12,
        weight=0.9,
        cond_temp=-25,
        delta_temp=20,
        cond_humidity=45,
        delta_humidity=15,
        cond_fertility=15,
        delta_fertility=15,
        stats=pulse(
            cond_t=-2,
            glob_m=1,
            glob_t=-4,
            glob_f=-1,
            loc_m=1,
            loc_t=-2,
            falloff=1.0,
        ),
    ),
    C(
        "wildnature:mossy_caves",
        "Mossy wet fertile caves.",
        generation_type="transition",
        placement_type="full_region",
        climates=["wet", "normal"],
        temperature=0.54,
        vegetation_density=0.65,
        weight=0.9,
        cond_temp=40,
        delta_temp=20,
        cond_humidity=70,
        delta_humidity=15,
        cond_fertility=130,
        delta_fertility=30,
        stats=pulse(cond_m=1, cond_f=2, glob_m=3, glob_f=3, loc_m=2, loc_f=2, falloff=0.9),
    ),
    C(
        "conquest:limestone_caves",
        "Barren limestone.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.47,
        vegetation_density=0.35,
        weight=0.9,
        cond_temp=30,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=35,
        delta_fertility=20,
        stats=pulse(glob_m=-1, glob_f=-2, loc_m=-1, loc_f=-1, falloff=1.1),
    ),
    C(
        "conquest:chalk_caves",
        "Barren chalk.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.44,
        vegetation_density=0.28,
        weight=0.8,
        cond_temp=28,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=35,
        delta_fertility=20,
        stats=pulse(glob_m=-1, glob_f=-2, loc_m=-1, loc_f=-1, falloff=1.1),
    ),
    C(
        "conquest:karst_caves",
        "Barren karst stone.",
        generation_type="transition",
        placement_type="full_region",
        climates=["normal"],
        temperature=0.50,
        vegetation_density=0.40,
        weight=0.9,
        cond_temp=30,
        delta_temp=20,
        cond_humidity=40,
        delta_humidity=15,
        cond_fertility=35,
        delta_fertility=20,
        stats=pulse(glob_m=-1, glob_f=-2, loc_m=-1, loc_f=-1, falloff=1.1),
    ),
]


def _biome_to_relpath(biome_id: str) -> Path:
    if ":" not in biome_id:
        raise ValueError(f"biome id missing namespace: {biome_id}")
    ns, path = biome_id.split(":", 1)
    return Path(ns) / f"{path}.json"


def _strip_note(entry: dict[str, Any]) -> dict[str, Any]:
    out = {k: v for k, v in entry.items() if not k.startswith("_")}
    return out


def write_json(path: Path, body: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(body, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")


def write_readme() -> None:
    readme = SURFACE_ROOT / "_CURATED_README.txt"
    readme.write_text(
        "\n".join(
            [
                "Hand-authored ideal biome defaults for NewTerraForged.",
                "",
                "These by_id / Cave Biomes JSON files are generated by",
                "tools/generate_curated_defaults.py from an EXPLICIT catalog",
                "(every biome is a written dict with a human note).",
                "",
                "Surface resolution: player Biomes/*.json → Defaults/by_id →",
                "by_name templates → emergency BiomeRuleAutogen only.",
                "",
                "Cave resolution: player Cave_configs/Biomes/*.json → bundled",
                "classpath curated Biomes (seeded on sync) → toml migrate →",
                "CaveCondNameDefaults only as last-resort fill for missing Cond axes.",
                "",
                "Edit the Python catalog and re-run the generator — do not treat",
                "runtime autogen as curated truth.",
                "",
            ]
        ),
        encoding="utf-8",
    )


CURATED_REVISION = 1


def main() -> None:
    # Validate uniqueness
    surface_ids = [e["biome"] for e in SURFACE]
    cave_ids = [e["biome"] for e in CAVES]
    if len(surface_ids) != len(set(surface_ids)):
        raise SystemExit("Duplicate surface biome ids in catalog")
    if len(cave_ids) != len(set(cave_ids)):
        raise SystemExit("Duplicate cave biome ids in catalog")

    surface_n = 0
    for entry in SURFACE:
        body = _strip_note(entry)
        if not body.get("terrains"):
            raise SystemExit(f"Empty terrains for {body.get('biome')}")
        rel = _biome_to_relpath(body["biome"])
        write_json(SURFACE_BY_ID / rel, body)
        surface_n += 1

    cave_n = 0
    index_lines: list[str] = []
    for entry in CAVES:
        body = _strip_note(entry)
        body["curated_revision"] = CURATED_REVISION
        for key in (
            "cond_temp",
            "delta_temp",
            "cond_humidity",
            "delta_humidity",
            "cond_fertility",
            "delta_fertility",
        ):
            if key not in body:
                raise SystemExit(f"Missing {key} for {body.get('biome')}")
        rel = _biome_to_relpath(body["biome"])
        write_json(CAVE_ROOT / rel, body)
        index_lines.append(rel.as_posix())
        cave_n += 1

    index_path = CAVE_ROOT / "_CURATED_INDEX.txt"
    index_path.write_text(
        "\n".join(
            [
                f"# curated_revision={CURATED_REVISION}",
                "# relative paths under Cave_configs/Biomes/",
                *sorted(index_lines),
                "",
            ]
        ),
        encoding="utf-8",
    )

    write_readme()

    print(f"Wrote {surface_n} surface by_id rules under {SURFACE_BY_ID}")
    print(f"Wrote {cave_n} cave biome rules under {CAVE_ROOT}")
    print(f"Wrote {index_path}")
    print(f"Wrote {SURFACE_ROOT / '_CURATED_README.txt'}")


if __name__ == "__main__":
    main()
