package com.terraforged.mod.worldgen.cave;

import java.util.Collections;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import net.minecraft.resources.ResourceLocation;

/**
 * Per-biome cave placement rule (JSON under Cave_configs/Biomes/).
 * Condition climate uses human scales: t° (−50..150), Humidity% (0..100), Fertility (0..200)
 * matched as target ± delta against the regional pool.
 */
public final class CaveBiomeRule {
    public enum Dimension {
        OVERWORLD,
        NETHER;

        public static Dimension fromAlias(String raw) {
            if (raw == null || raw.isBlank()) {
                return OVERWORLD;
            }
            String s = raw.trim().toLowerCase(Locale.ROOT);
            if (s.startsWith("neth") || s.equals("n")) {
                return NETHER;
            }
            return OVERWORLD;
        }

        public String alias() {
            return this == NETHER ? "nether" : "overworld";
        }

        public String label() {
            return this == NETHER ? "Nether" : "Overworld";
        }
    }

    public final String biome;
    public final CaveBiomeCategory category;
    public final CavePlacementType placementType;
    public final Set<CaveClimateType> climates;
    public final Set<String> systems;
    public final Dimension dimension;
    public final float temperature;
    public final float vegetationDensity;
    public final float weight;
    public final float ceilingPatchMin;
    public final float ceilingPatchMax;
    public final float islandMaxRadius;
    public final CaveBiomeStats stats;
    public final boolean statGenerator;
    public final boolean autoGenerated;

    /** Condition targets (human scale). {@link CaveClimateScale#UNSET} = no target filter. */
    public final int condTemp;
    public final int deltaTemp;
    public final int condHumidity;
    public final int deltaHumidity;
    public final int condFertility;
    public final int deltaFertility;

    public CaveBiomeRule(
            String biome,
            CaveBiomeCategory category,
            CavePlacementType placementType,
            Set<CaveClimateType> climates,
            Set<String> systems,
            float temperature,
            float vegetationDensity,
            float weight,
            float ceilingPatchMin,
            float ceilingPatchMax,
            float islandMaxRadius,
            CaveBiomeStats stats,
            boolean statGenerator,
            boolean autoGenerated
    ) {
        this(biome, category, placementType, climates, systems, Dimension.OVERWORLD,
                temperature, vegetationDensity, weight, ceilingPatchMin, ceilingPatchMax, islandMaxRadius,
                stats, statGenerator, autoGenerated,
                CaveClimateScale.UNSET, CaveClimateScale.DEFAULT_DELTA_TEMP,
                CaveClimateScale.UNSET, CaveClimateScale.DEFAULT_DELTA_HUM,
                CaveClimateScale.UNSET, CaveClimateScale.DEFAULT_DELTA_FERT,
                true);
    }

    public CaveBiomeRule(
            String biome,
            CaveBiomeCategory category,
            CavePlacementType placementType,
            Set<CaveClimateType> climates,
            Set<String> systems,
            Dimension dimension,
            float temperature,
            float vegetationDensity,
            float weight,
            float ceilingPatchMin,
            float ceilingPatchMax,
            float islandMaxRadius,
            CaveBiomeStats stats,
            boolean statGenerator,
            boolean autoGenerated
    ) {
        this(biome, category, placementType, climates, systems, dimension,
                temperature, vegetationDensity, weight, ceilingPatchMin, ceilingPatchMax, islandMaxRadius,
                stats, statGenerator, autoGenerated,
                CaveClimateScale.UNSET, CaveClimateScale.DEFAULT_DELTA_TEMP,
                CaveClimateScale.UNSET, CaveClimateScale.DEFAULT_DELTA_HUM,
                CaveClimateScale.UNSET, CaveClimateScale.DEFAULT_DELTA_FERT,
                true);
    }

    public CaveBiomeRule(
            String biome,
            CaveBiomeCategory category,
            CavePlacementType placementType,
            Set<CaveClimateType> climates,
            Set<String> systems,
            Dimension dimension,
            float temperature,
            float vegetationDensity,
            float weight,
            float ceilingPatchMin,
            float ceilingPatchMax,
            float islandMaxRadius,
            CaveBiomeStats stats,
            boolean statGenerator,
            boolean autoGenerated,
            int condTemp,
            int deltaTemp,
            int condHumidity,
            int deltaHumidity,
            int condFertility,
            int deltaFertility
    ) {
        this(biome, category, placementType, climates, systems, dimension,
                temperature, vegetationDensity, weight, ceilingPatchMin, ceilingPatchMax, islandMaxRadius,
                stats, statGenerator, autoGenerated,
                condTemp, deltaTemp, condHumidity, deltaHumidity, condFertility, deltaFertility,
                false);
    }

    private CaveBiomeRule(
            String biome,
            CaveBiomeCategory category,
            CavePlacementType placementType,
            Set<CaveClimateType> climates,
            Set<String> systems,
            Dimension dimension,
            float temperature,
            float vegetationDensity,
            float weight,
            float ceilingPatchMin,
            float ceilingPatchMax,
            float islandMaxRadius,
            CaveBiomeStats stats,
            boolean statGenerator,
            boolean autoGenerated,
            int condTemp,
            int deltaTemp,
            int condHumidity,
            int deltaHumidity,
            int condFertility,
            int deltaFertility,
            boolean deriveTargetsFromLegacy
    ) {
        this.biome = biome == null ? "" : biome.trim().toLowerCase(Locale.ROOT);
        this.category = category == null ? CaveBiomeCategory.PRIMARY : category;
        this.placementType = placementType == null ? CavePlacementType.FULL_REGION : placementType;
        this.climates = climates == null || climates.isEmpty()
                ? Set.of()
                : Collections.unmodifiableSet(EnumSet.copyOf(climates));
        this.systems = systems == null || systems.isEmpty()
                ? Set.of()
                : Collections.unmodifiableSet(new LinkedHashSet<>(systems));
        this.dimension = dimension == null ? Dimension.OVERWORLD : dimension;
        this.temperature = temperature;
        this.vegetationDensity = vegetationDensity;
        this.weight = weight;
        this.ceilingPatchMin = ceilingPatchMin;
        this.ceilingPatchMax = ceilingPatchMax;
        this.islandMaxRadius = islandMaxRadius;
        this.stats = stats == null ? CaveBiomeStats.EMPTY : stats;
        this.statGenerator = statGenerator;
        this.autoGenerated = autoGenerated;

        if (deriveTargetsFromLegacy) {
            int[] derived = deriveFromStats(this.stats);
            int t = derived[0];
            int dT = CaveClimateScale.DEFAULT_DELTA_TEMP;
            int h = derived[1];
            int dH = CaveClimateScale.DEFAULT_DELTA_HUM;
            int f = derived[2];
            int dF = CaveClimateScale.DEFAULT_DELTA_FERT;
            try {
                ResourceLocation id = new ResourceLocation(biome);
                int[] merged = CaveCondNameDefaults.mergeWithExisting(id, t, dT, h, dH, f, dF);
                t = merged[0];
                dT = merged[1];
                h = merged[2];
                dH = merged[3];
                f = merged[4];
                dF = merged[5];
            } catch (Exception ignored) {
            }
            this.condTemp = t;
            this.deltaTemp = dT;
            this.condHumidity = h;
            this.deltaHumidity = dH;
            this.condFertility = f;
            this.deltaFertility = dF;
        } else {
            this.condTemp = condTemp;
            this.deltaTemp = Math.max(0, deltaTemp);
            this.condHumidity = condHumidity;
            this.deltaHumidity = Math.max(0, deltaHumidity);
            this.condFertility = condFertility;
            this.deltaFertility = Math.max(0, deltaFertility);
        }
    }

    private static int[] deriveFromStats(CaveBiomeStats s) {
        CaveStatVector c = s.conditions();
        // Per-axis: legacy −10 sentinel means "no requirement" → UNSET (filled by CaveCondNameDefaults).
        int t = c.temperature() <= -9.5F ? CaveClimateScale.UNSET : CaveClimateScale.tempFromInternal(c.temperature());
        int h = c.moisture() <= -9.5F ? CaveClimateScale.UNSET : CaveClimateScale.humidityFromInternal(c.moisture());
        int f = c.fertility() <= -9.5F ? CaveClimateScale.UNSET : CaveClimateScale.fertilityFromInternal(c.fertility());
        return new int[]{t, h, f};
    }

    public boolean hasCondTargets() {
        return condTemp != CaveClimateScale.UNSET
                || condHumidity != CaveClimateScale.UNSET
                || condFertility != CaveClimateScale.UNSET;
    }

    public boolean matchesPool(CaveStatVector pool) {
        try {
            ResourceLocation id = new ResourceLocation(biome);
            return CaveClimateScale.matchesRuleTargets(
                    id, pool, condTemp, deltaTemp, condHumidity, deltaHumidity, condFertility, deltaFertility);
        } catch (Exception e) {
            return true;
        }
    }

    public CaveBiomeRule withStats(CaveBiomeStats nextStats, boolean generator) {
        return copy(climates, systems, dimension, temperature, vegetationDensity, weight, nextStats, generator,
                condTemp, deltaTemp, condHumidity, deltaHumidity, condFertility, deltaFertility);
    }

    public CaveBiomeRule withPlacement(float temp, float veg, float wt) {
        return copy(climates, systems, dimension, temp, veg, wt, stats, statGenerator,
                condTemp, deltaTemp, condHumidity, deltaHumidity, condFertility, deltaFertility);
    }

    public CaveBiomeRule withDimension(Dimension dim) {
        return copy(climates, systems, dim, temperature, vegetationDensity, weight, stats, statGenerator,
                condTemp, deltaTemp, condHumidity, deltaHumidity, condFertility, deltaFertility);
    }

    public CaveBiomeRule withCondTargets(
            int t, int dT, int h, int dH, int f, int dF
    ) {
        // Keep legacy conditions vector in sync for any remaining −10..10 consumers.
        CaveBiomeStats synced = stats
                .withAxis("conditions", "temp", t == CaveClimateScale.UNSET ? -10.0F : CaveClimateScale.tempToInternal(t));
        synced = synced.withAxis("conditions", "moist", h == CaveClimateScale.UNSET ? -10.0F : CaveClimateScale.humidityToInternal(h));
        synced = synced.withAxis("conditions", "fert", f == CaveClimateScale.UNSET ? -10.0F : CaveClimateScale.fertilityToInternal(f));
        return new CaveBiomeRule(
                biome, category, placementType, climates, systems, dimension,
                temperature, vegetationDensity, weight, ceilingPatchMin, ceilingPatchMax, islandMaxRadius,
                synced, statGenerator, false,
                t, dT, h, dH, f, dF
        );
    }

    public CaveBiomeRule withClimatesSystems(CaveBiomeCategory cat, Set<CaveClimateType> climates, Set<String> systems) {
        return new CaveBiomeRule(
                biome, cat, placementType, climates, systems, dimension,
                temperature, vegetationDensity, weight, ceilingPatchMin, ceilingPatchMax, islandMaxRadius,
                stats, statGenerator, false,
                condTemp, deltaTemp, condHumidity, deltaHumidity, condFertility, deltaFertility
        );
    }

    private CaveBiomeRule copy(
            Set<CaveClimateType> climates,
            Set<String> systems,
            Dimension dimension,
            float temperature,
            float vegetationDensity,
            float weight,
            CaveBiomeStats stats,
            boolean generator,
            int t, int dT, int h, int dH, int f, int dF
    ) {
        return new CaveBiomeRule(
                biome, category, placementType, climates, systems, dimension,
                temperature, vegetationDensity, weight, ceilingPatchMin, ceilingPatchMax, islandMaxRadius,
                stats, generator, false,
                t, dT, h, dH, f, dF
        );
    }

    public boolean allowsSystem(String system) {
        if (systems.isEmpty()) {
            return true;
        }
        return systems.contains(system.toLowerCase(Locale.ROOT));
    }

    public boolean allowsClimate(CaveClimateType climate) {
        if (climates.isEmpty()) {
            return true;
        }
        return climates.contains(climate);
    }

    public Map<String, Object> debugMap() {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("biome", biome);
        m.put("generation_type", category.name().toLowerCase(Locale.ROOT));
        m.put("dimension", dimension.alias());
        return m;
    }

    public static CaveBiomeCategory categoryFromGeneration(String raw) {
        if (raw == null || raw.isBlank()) {
            return CaveBiomeCategory.PRIMARY;
        }
        String s = raw.trim().toLowerCase(Locale.ROOT);
        return switch (s) {
            case "transition" -> CaveBiomeCategory.TRANSITION;
            case "patch", "special" -> CaveBiomeCategory.SPECIAL;
            case "coastal", "coast" -> CaveBiomeCategory.COASTAL;
            default -> CaveBiomeCategory.PRIMARY;
        };
    }

    public static String generationAlias(CaveBiomeCategory cat) {
        if (cat == null) {
            return "primary";
        }
        return switch (cat) {
            case TRANSITION -> "transition";
            case SPECIAL -> "patch";
            case COASTAL -> "coastal";
            default -> "primary";
        };
    }

    public static List<String> allClimateAliases() {
        return List.of("hot", "volcanic", "dry", "humid", "cold", "normal");
    }

    public static List<String> allSystems() {
        return List.of("mega", "giga", "synapse");
    }

    public static List<String> allGenerationTypes() {
        return List.of("primary", "transition", "patch", "coastal");
    }
}
