package com.terraforged.mod.worldgen.cave;

import java.util.Collections;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Per-biome cave placement rule (JSON under Cave_configs/Biomes/).
 * generation_type: primary | transition | patch | coastal
 * climates: hot, volcanic, dry, humid, cold, normal (empty = path heuristics)
 * systems: mega, giga, synapse (empty = all)
 */
public final class CaveBiomeRule {
    public final String biome;
    public final CaveBiomeCategory category;
    public final CavePlacementType placementType;
    public final Set<CaveClimateType> climates;
    public final Set<String> systems;
    public final float temperature;
    public final float vegetationDensity;
    public final float weight;
    public final float ceilingPatchMin;
    public final float ceilingPatchMax;
    public final float islandMaxRadius;
    public final CaveBiomeStats stats;
    public final boolean statGenerator;
    public final boolean autoGenerated;

    public CaveBiomeRule(
            String biome,
            CaveBiomeCategory category,
            CavePlacementType placementType,
            Set<CaveClimateType> climates,
            Set<String> systems,
            float temperature,
            float vegetationDensity,
            float weight,
            float ceilingPatchMin,
            float ceilingPatchMax,
            float islandMaxRadius,
            CaveBiomeStats stats,
            boolean statGenerator,
            boolean autoGenerated
    ) {
        this.biome = biome == null ? "" : biome.trim().toLowerCase(Locale.ROOT);
        this.category = category == null ? CaveBiomeCategory.PRIMARY : category;
        this.placementType = placementType == null ? CavePlacementType.FULL_REGION : placementType;
        this.climates = climates == null || climates.isEmpty()
                ? Set.of()
                : Collections.unmodifiableSet(EnumSet.copyOf(climates));
        this.systems = systems == null || systems.isEmpty()
                ? Set.of()
                : Collections.unmodifiableSet(new LinkedHashSet<>(systems));
        this.temperature = temperature;
        this.vegetationDensity = vegetationDensity;
        this.weight = weight;
        this.ceilingPatchMin = ceilingPatchMin;
        this.ceilingPatchMax = ceilingPatchMax;
        this.islandMaxRadius = islandMaxRadius;
        this.stats = stats == null ? CaveBiomeStats.EMPTY : stats;
        this.statGenerator = statGenerator;
        this.autoGenerated = autoGenerated;
    }

    public boolean allowsSystem(String system) {
        if (systems.isEmpty()) {
            return true;
        }
        return systems.contains(system.toLowerCase(Locale.ROOT));
    }

    public boolean allowsClimate(CaveClimateType climate) {
        if (climates.isEmpty()) {
            return true; // defer to path heuristics
        }
        return climates.contains(climate);
    }

    public Map<String, Object> debugMap() {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("biome", biome);
        m.put("generation_type", category.name().toLowerCase(Locale.ROOT));
        return m;
    }

    public static CaveBiomeCategory categoryFromGeneration(String raw) {
        if (raw == null || raw.isBlank()) {
            return CaveBiomeCategory.PRIMARY;
        }
        String s = raw.trim().toLowerCase(Locale.ROOT);
        return switch (s) {
            case "transition" -> CaveBiomeCategory.TRANSITION;
            case "patch", "special" -> CaveBiomeCategory.SPECIAL;
            case "coastal", "coast" -> CaveBiomeCategory.COASTAL;
            default -> CaveBiomeCategory.PRIMARY;
        };
    }

    public static String generationAlias(CaveBiomeCategory cat) {
        if (cat == null) {
            return "primary";
        }
        return switch (cat) {
            case TRANSITION -> "transition";
            case SPECIAL -> "patch";
            case COASTAL -> "coastal";
            default -> "primary";
        };
    }

    public static List<String> allClimateAliases() {
        return List.of("hot", "volcanic", "dry", "humid", "cold", "normal");
    }

    public static List<String> allSystems() {
        return List.of("mega", "giga", "synapse");
    }

    public static List<String> allGenerationTypes() {
        return List.of("primary", "transition", "patch", "coastal");
    }
}
